const items=[
    {
            id:`001`,
            image:`1.jpg`,
            rating:{
                stars:4.5,
                noofReviews: 1400,
            },
            company_name:`Levis`,
            item_name:`T-Shirt`,
            current_price: 606,
            original_price: 1045,
            discount_percentage:42,
        },

 {
            id:`002`,
            image:`2.jpg`,
            rating:{
                stars:4.5,
                noofReviews: 1400,
            },
            company_name:`Levis`,
            item_name:`T-Shirt`,
            current_price: 606,
            original_price: 1045,
            discount_percentage:42,
        },
        {
            id:`003`,
            image:`3.jpg`,
            rating:{
                stars:4.5,
                noofReviews: 1400,
            },
            company_name:`Levis`,
            item_name:`T-Shirt`,
            current_price: 606,
            original_price: 1045,
            discount_percentage:42,
        },
        {
            id:`004`,
            image:`4.jpg`,
            rating:{
                stars:4.5,
                noofReviews: 1400,
            },
            company_name:`Levis`,
            item_name:`T-Shirt`,
            current_price: 606,
            original_price: 1045,
            discount_percentage:42,
        },
        {
            id:`005`,
            image:`5.jpg`,
            rating:{
                stars:4.5,
                noofReviews: 1400,
            },
            company_name:`Levis`,
            item_name:`T-Shirt`,
            current_price: 606,
            original_price: 1045,
            discount_percentage:42,
        },
        {
            id:`006`,
            image:`6.jpg`,
            rating:{
                stars:4.5,
                noofReviews: 1400,
            },
            company_name:`Levis`,
            item_name:`T-Shirt`,
            current_price: 606,
            original_price: 1045,
            discount_percentage:42,
        },
        {
            id:`007`,
            image:`7.jpg`,
            rating:{
                stars:4.5,
                noofReviews: 1400,
            },
            company_name:`Levis`,
            item_name:`T-Shirt`,
            current_price: 606,
            original_price: 1045,
            discount_percentage:42,
        },
        {
            id:`008`,
            image:`8.jpg`,
            rating:{
                stars:4.5,
                noofReviews: 1400,
            },
            company_name:`Levis`,
            item_name:`T-Shirt`,
            current_price: 606,
            original_price: 1045,
            discount_percentage:42,
        },
        {
            id:`009`,
            image:`9.jpg`,
            rating:{
                stars:4.5,
                noofReviews: 1400,
            },
            company_name:`Levis`,
            item_name:`T-Shirt`,
            current_price: 606,
            original_price: 1045,
            discount_percentage:42,
        },
        {
            id:`010`,
            image:`10.jpg`,
            rating:{
                stars:4.5,
                noofReviews: 1400,
            },
            company_name:`Levis`,
            item_name:`T-Shirt`,
            current_price: 606,
            original_price: 1045,
            discount_percentage:42,
        },
]